name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/req.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install -r req.txt

      - name: Run Django server
        run: |
          source venv/bin/activate
          cd mysite
          python3 manage.py runserver &
